version: '3'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_HOST
      - DATABASE_NAME
      - DATABASE_PORT
      - DATABASE_USER ${DATABASE_USER}
      - DATABASE_PASSWORD ${DATABASE_PASSWORD}
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - DATABASE_HOST
      - DATABASE_NAME
      - DATABASE_PORT
      - DATABASE_USER
      - DATABASE_PASSWORD
    ports:
      - 5432:5432

volumes:
    postgres_data:
