name: Backend CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.1
    - name: Install dependencies
      run: |
        cd backend
        make install
    - name: Lint with pylint
      run: |
        cd backend
        make lint
    - name: Test with pytest
      run: |
        cd backend
        make test
    - name: Format code
      run: |
        cd backend
        make format
    - name: Print secrets
      run: |
       echo "DATABASE_HOST = ${{ secrets.DATABASE_HOST }}"
       echo "DATABASE_NAME = ${{ secrets.DATABASE_NAME }}"
       echo "DATABASE_PORT = ${{ secrets.DATABASE_PORT }}"
       echo "DATABASE_USER = ${{ secrets.DATABASE_USER }}"
       echo "DATABASE_PASSWORD = ${{ secrets.DATABASE_PASSWORD }}"
    - name: Build Containers
      run: |
        docker-compose up
      env:
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
